# Generated by Django 5.2.10 on 2026-01-15 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('diagnostic', models.CharField(blank=True, max_length=255)),
                ('instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_patient', models.CharField(max_length=32, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=150)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('sexe', models.CharField(blank=True, choices=[('F', 'Femme'), ('M', 'Homme')], max_length=1, null=True)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('zone', models.CharField(choices=[('GRAND_BASSAM', 'Grand-Bassam'), ('BONOUA', 'Bonoua')], default='GRAND_BASSAM', max_length=50)),
                ('antecedents', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nom', 'prenoms'],
            },
        ),
        migrations.CreateModel(
            name='LigneOrdonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament', models.CharField(max_length=255)),
                ('posologie', models.CharField(blank=True, max_length=255)),
                ('duree', models.CharField(blank=True, max_length=100)),
                ('commentaire', models.CharField(blank=True, max_length=255)),
                ('ordonnance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='patients.ordonnance')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances', to='patients.patient'),
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateTimeField()),
                ('motif', models.CharField(blank=True, max_length=255)),
                ('observation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='patients.patient')),
            ],
            options={
                'ordering': ['-date_consultation'],
            },
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField()),
                ('objet', models.CharField(blank=True, max_length=255)),
                ('statut', models.CharField(choices=[('PLANIFIE', 'Planifié'), ('EFFECTUE', 'Effectué'), ('ANNULE', 'Annulé')], default='PLANIFIE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='patients.patient')),
            ],
            options={
                'ordering': ['-date_heure'],
            },
        ),
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('statut', models.CharField(choices=[('SUCCES', 'Succès'), ('ECHEC', 'Échec')], max_length=10)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('provider_message_id', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rendez_vous', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='patients.rendezvous')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuiviCPN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(choices=[(1, 'CPN1'), (2, 'CPN2'), (3, 'CPN3'), (4, 'CPN4')])),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis_cpn', to='patients.patient')),
            ],
            options={
                'ordering': ['patient', 'numero'],
                'unique_together': {('patient', 'numero')},
            },
        ),
    ]
