# Generated by Django 5.2.10 on 2026-01-16 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasSuivi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_cas', models.CharField(choices=[('VIH', 'VIH/Sida'), ('TB', 'Tuberculose')], max_length=10)),
                ('statut', models.CharField(choices=[('SUSPECT', 'Suspect'), ('CONFIRME', 'Confirmé'), ('SUIVI', 'En suivi'), ('CLOTURE', 'Clôturé')], default='SUIVI', max_length=10)),
                ('date_signalement', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cas_suivi', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
