# Generated by Django 5.2.10 on 2026-01-15 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('MEDECIN', 'Médecin'), ('SAGE_FEMME', 'Sage-femme'), ('AGENT_COMMUNAUTAIRE', 'Agent communautaire'), ('PSYCHOLOGUE', 'Psychologue')], default='AGENT_COMMUNAUTAIRE', max_length=30)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
