# Generated by Django 5.2.10 on 2026-01-19 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('MEDECIN', 'Médecin'), ('SAGE_FEMME', 'Sage-femme'), ('AGENT_COMMUNAUTAIRE', 'Agent communautaire'), ('PSYCHOLOGUE', 'Psychologue'), ('PATIENT', 'Patient')], default='AGENT_COMMUNAUTAIRE', max_length=30),
        ),
    ]
