# Generated by Django 5.2.10 on 2026-01-15 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pathologie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='DossierCommunautaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_diagnostic', models.DateField()),
                ('statut', models.CharField(choices=[('SUIVI', 'En suivi'), ('STABLE', 'Stable'), ('TERMINE', 'Terminé'), ('DECEDE', 'Décédé')], default='SUIVI', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers_communautaires', to='patients.patient')),
                ('pathologie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dossiers', to='community.pathologie')),
            ],
            options={
                'ordering': ['-date_diagnostic', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SuiviCommunautaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('observation', models.TextField(blank=True)),
                ('traitement', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='community.dossiercommunautaire')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
